In [ ]:
# https://www.youtube.com/watch?v=OY4eQrekQvs&t=1292s
# https://www.youtube.com/watch?v=qxpKCBV60U4&t=411s

In [75]:
pip install pandas

Requirement already satisfied: pandas in ./lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in ./lib/python3.11/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [76]:
import pandas as pd

Read datasetOne, see what columns there are and what column I'll need for these tasks.

In [77]:
dataset_one = pd.read_csv('datasetOne.csv')
dataset_one

,Food_items,Breakfast,Lunch,Dinner,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars
0,Asparagus Cooked,0,1,1,,22,0.2,2.4,0.91,23.0,14,224.0,4.1,2.0,0,1.3
1,Avocados,1,0,0,0,160,15.0,2.0,0.55,12.0,7,485.0,8.5,6.7,0,0.7
2,Bananas,1,0,0,0,89,0.3,1.1,0.26,5.0,1,358.0,23.0,2.6,0,12.0
3,Bagels made in wheat,0,1,1,0,250,1.5,10.0,2.76,20.0,439,165.0,49.0,4.1,0,6.1
4,Berries,1,0,0,0,349,0.4,14.0,6.80,190.0,298,77.0,77.0,13.0,0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Vanilla Ice cream,0,0,1,0,207,11.0,3.5,0.09,128.0,80,199.0,24.0,0.7,0,21.0
85,Strawberry Icecream,0,0,1,0,192,8.4,3.2,0.21,120.0,60,188.0,28.0,0.9,0,0.0
86,Marshmallows,0,0,1,0,318,0.2,1.8,0.23,3.0,80,5.0,81.0,0.1,0,58.0
87,Chocolate milk,1,0,0,0,535,30.0,7.7,2.35,189.0,79,372.0,59.0,3.4,0,52.0
88,Rice Pudding,0,0,1,0,376,0.1,2.7,1.79,14.0,366,5.0,91.0,0.7,0,0.0

In [78]:
dataset_one.columns

Index(['Food_items', 'Breakfast', 'Lunch', 'Dinner', 'VegNovVeg', 'Calories',
       'Fats', 'Proteins', 'Iron', 'Calcium', 'Sodium', 'Potassium',
       'Carbohydrates', 'Fibre', 'VitaminD', 'Sugars'],
      dtype='object')

Choose the column I needed and make all text lower case to keep all data cohesive.

In [79]:
dataset_one['Food_items'] = dataset_one['Food_items'].str.lower()

In [80]:
dataset_one_subset = dataset_one['Food_items']
dataset_one_subset

0         asparagus cooked
1                 avocados
2                  bananas
3     bagels made in wheat
4                  berries
              ...
84       vanilla ice cream
85     strawberry icecream
86            marshmallows
87          chocolate milk
88            rice pudding
Name: Food_items, Length: 89, dtype: object

Drop any reaccuring items to ensure there are no multiples.

In [89]:
dataset_one_subset = dataset_one_subset.drop_duplicates()
dataset_one_subset

0         asparagus cooked
1                 avocados
2                  bananas
3     bagels made in wheat
4                  berries
              ...
84       vanilla ice cream
85     strawberry icecream
86            marshmallows
87          chocolate milk
88            rice pudding
Name: Food_items, Length: 89, dtype: object

Repeat this basic reading of the datasets and cleaning with the other CSV's I downloaded from [Kaggle](https://www.kaggle.com/datasets/dtamindu/food-items-with-nutritional-info)

In [81]:
dataset_two = pd.read_csv('datasetTwo.csv')
dataset_two

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,crispy chicken strips tyson,145,6.000,7.700,14.500,1.000,0.0,0.0,0.000,0.0,...,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.000,6.000
1,nectarine,66,0.500,0.066,0.100,0.200,15.8,11.8,1.600,2.6,...,0.081,9.000,0.100,0.4,13.500,0.002,39.0,301.500,0.000,20.735
2,kiwifruit gold,51,0.200,0.008,0.099,0.051,12.8,10.0,0.800,1.1,...,13.800,0.100,0.200,9.7,0.072,20.300,255.2,0.003,0.077,159.686
3,prickly pear raw,8,0.072,0.000,0.000,0.000,1.9,0.2,0.001,1.0,...,34.200,0.051,0.021,13.1,0.100,2.100,24.7,0.023,0.073,39.263
4,pineapple,45,0.100,0.074,0.001,0.087,11.8,8.9,0.500,1.3,...,0.061,11.700,0.091,0.3,10.800,0.800,7.2,98.100,0.061,13.970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,beets canned,69,0.200,0.017,0.060,0.099,16.2,13.2,2.000,3.0,...,32.000,0.200,1.500,39.4,0.600,39.400,349.3,0.063,0.600,61.800
121,stewed tomatoes canned,66,0.500,0.078,0.058,0.200,15.8,9.0,2.300,2.6,...,0.039,86.700,0.300,3.4,30.600,0.200,51.0,527.900,0.082,21.684
122,tomato paste canned,215,1.200,0.300,0.200,0.400,49.5,31.9,11.300,10.7,...,94.300,1.000,7.800,110.0,0.800,217.500,2656.7,0.070,1.700,232.200
123,bacon ranch salad mcdonalds,389,20.100,5.200,7.900,5.200,19.4,4.9,28.100,3.2,...,146.700,0.000,1.900,0.0,0.000,0.000,0.0,0.000,0.000,250.300
124,caesar salad with grilled chicken mcdonalds,201,5.600,3.000,1.500,0.600,11.3,4.8,29.100,3.3,...,189.400,0.000,1.800,0.0,0.000,0.000,754.8,0.000,0.000,271.900

In [82]:
dataset_two_subset = dataset_two['food']
dataset_two_subset

0                      crispy chicken strips tyson
1                                        nectarine
2                                   kiwifruit gold
3                                 prickly pear raw
4                                        pineapple
                          ...
120                                   beets canned
121                         stewed tomatoes canned
122                            tomato paste canned
123                    bacon ranch salad mcdonalds
124    caesar salad with grilled chicken mcdonalds
Name: food, Length: 125, dtype: object

In [90]:
dataset_two_subset = dataset_two_subset.drop_duplicates()
dataset_two_subset

0                      crispy chicken strips tyson
1                                        nectarine
2                                   kiwifruit gold
3                                 prickly pear raw
4                                        pineapple
                          ...
120                                   beets canned
121                         stewed tomatoes canned
122                            tomato paste canned
123                    bacon ranch salad mcdonalds
124    caesar salad with grilled chicken mcdonalds
Name: food, Length: 125, dtype: object

In [83]:
dataset_three = pd.read_csv('datasetThree.csv')
dataset_three

                         Food              Serving Calories
0                   Artichoke  1 artichoke (128 g)   60 cal
1                     Arugula         1 leaf (2 g)    1 cal
2                   Asparagus       1 spear (12 g)    2 cal
3                   Aubergine  1 aubergine (458 g)  115 cal
4                    Beetroot        1 beet (82 g)   35 cal
..                        ...                  ...      ...
557  Wendy’s Jr. Cheeseburger     1 burger (129 g)  290 cal
558  Wendy’s Son of Baconator     1 burger (218 g)  700 cal
559                   Whopper     1 burger (291 g)  672 cal
560                    Zinger   1 sandwich (202 g)  517 cal
561             Zinger Burger   1 sandwich (202 g)  517 cal

[562 rows x 3 columns]

In [84]:
dataset_three['Food'] = dataset_three['Food'].str.lower()

In [85]:
dataset_three_subset = dataset_three['Food']
dataset_three_subset

0                     artichoke
1                       arugula
2                     asparagus
3                     aubergine
4                      beetroot
                 ...
557    wendy’s jr. cheeseburger
558    wendy’s son of baconator
559                     whopper
560                      zinger
561               zinger burger
Name: Food, Length: 562, dtype: object

In [91]:
dataset_three_subset = dataset_three_subset.drop_duplicates()
dataset_three_subset

0                     artichoke
1                       arugula
2                     asparagus
3                     aubergine
4                      beetroot
                 ...
557    wendy’s jr. cheeseburger
558    wendy’s son of baconator
559                     whopper
560                      zinger
561               zinger burger
Name: Food, Length: 541, dtype: object

In [86]:
dataset_four = pd.read_csv("datasetFour.csv", on_bad_lines="skip")
dataset_four

,Food,ood,Od,D,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,whole milk,butter,yogurt,rice,abrasive cleaner,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9829,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,whipped/sour cream,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9830,cooking chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9831,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,cling film/bags,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9832,semi-finished bread,bottled water,soda,bottled beer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9833,chicken,tropical fruit,other vegetables,vinegar,shopping bags,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
dataset_four.columns

Index(['Food', 'ood', 'Od', 'D', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31'],
      dtype='object')

In [88]:
dataset_four_subset = dataset_four['Food']
dataset_four_subset

0            tropical fruit
1                whole milk
2                 pip fruit
3          other vegetables
4                whole milk
               ...
9829                sausage
9830      cooking chocolate
9831                chicken
9832    semi-finished bread
9833                chicken
Name: Food, Length: 9834, dtype: object

In [92]:
dataset_four_subset = dataset_four_subset.drop_duplicates()
dataset_four_subset

0         tropical fruit
1             whole milk
2              pip fruit
3       other vegetables
5             rolls/buns
              ...
7636            cake bar
7691               honey
8381                 jam
8705     kitchen utensil
9502      flower (seeds)
Name: Food, Length: 158, dtype: object

Use concatenation to take all the columns and join them together as one big column. A big food dataset like this will hopefully allow for clearer and more accurate results when training the models.

In [93]:
all_foods = pd.concat([
    dataset_one_subset,
    dataset_two_subset,
    dataset_three_subset,
    dataset_four_subset
], ignore_index=True)

Clean again like earlier to ensure everything is cohesive.

In [94]:
all_foods = all_foods.str.lower()

In [95]:
all_foods = all_foods.drop_duplicates()

Name column.

In [96]:
all_foods_df = pd.DataFrame({'Food': all_foods})

In [97]:
all_foods_df

                     Food
0        asparagus cooked
1                avocados
2                 bananas
3    bagels made in wheat
4                 berries
..                    ...
907      organic products
908              cake bar
910                   jam
911       kitchen utensil
912        flower (seeds)

[872 rows x 1 columns]

Save to CSV.

In [99]:
all_foods_df.to_csv('Food.csv', index=False)