In [11]:
import pandas as pd

In [12]:
training_data = pd.read_csv("foodTrainingSubset.csv", header=0)
training_data

                   Food                             Categories
0             asparagus                                Produce
1              avocados                                Produce
2               bananas                                Produce
3     wholewheat bagels                        Breads & Grains
4            white buns                        Breads & Grains
...                 ...                                    ...
1051         Batteries   Household Supplies and Non-Food Items
1052       Sponges pack  Household Supplies and Non-Food Items
1053      Rubber gloves  Household Supplies and Non-Food Items
1054    Food containers  Household Supplies and Non-Food Items
1055            Napkins  Household Supplies and Non-Food Items

[1056 rows x 2 columns]

In [13]:
training_data.columns

Index(['Food', 'Categories'], dtype='object')

Making everything a string type and all in lower case.

In [14]:
training_data["Food"] = training_data["Food"].astype(str).str.lower()
training_data["Categories"] = training_data["Categories"].astype(str).str.lower()
training_data

                   Food                             Categories
0             asparagus                                produce
1              avocados                                produce
2               bananas                                produce
3     wholewheat bagels                        breads & grains
4            white buns                        breads & grains
...                 ...                                    ...
1051         batteries   household supplies and non-food items
1052       sponges pack  household supplies and non-food items
1053      rubber gloves  household supplies and non-food items
1054    food containers  household supplies and non-food items
1055            napkins  household supplies and non-food items

[1056 rows x 2 columns]

Make Categories back to obj after putting them in lowercase (ChatGPT)

In [15]:
training_data["Categories"].replace("nan", pd.NA, inplace=True)

/var/folders/6f/b_224x1j0055mmfds97sbh940000gn/T/ipykernel_66502/1931548385.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  training_data["Categories"].replace("nan", pd.NA, inplace=True)

Final cleaning, removing some fast-food terms, any empty rows, duplicates, whitespaces etc.

In [16]:
remove_words = [
    "cooked", "stewed", "canned", "arby's", "burger king", "mcdonalds",
    "mcdonald's", "mcflurry", "wendy's", "jr.", "zinger", "whopper",
    "subway", "pizza hut"
]

def clean_item(name):
    for w in remove_words:
        name = name.replace(w, "")
    return name.strip()

training_data["Food"] = training_data["Food"].apply(clean_item)

# remove empty rows (ChatGPT)
training_data = training_data[training_data["Food"].str.len() > 0]

In [17]:
training_data = training_data.drop_duplicates(subset="Food").reset_index(drop=True)

In [18]:
print(training_data)

                   Food                             Categories
0             asparagus                                produce
1              avocados                                produce
2               bananas                                produce
3     wholewheat bagels                        breads & grains
4            white buns                        breads & grains
...                 ...                                    ...
1027        cotton pads  household supplies and non-food items
1028          batteries  household supplies and non-food items
1029       sponges pack  household supplies and non-food items
1030      rubber gloves  household supplies and non-food items
1031    food containers  household supplies and non-food items

[1032 rows x 2 columns]

Dropping any empty rows and saving to CSV.

In [19]:
labeled_data = training_data.dropna(subset=["Categories"])
labeled_data

                   Food                             Categories
0             asparagus                                produce
1              avocados                                produce
2               bananas                                produce
3     wholewheat bagels                        breads & grains
4            white buns                        breads & grains
...                 ...                                    ...
1027        cotton pads  household supplies and non-food items
1028          batteries  household supplies and non-food items
1029       sponges pack  household supplies and non-food items
1030      rubber gloves  household supplies and non-food items
1031    food containers  household supplies and non-food items

[1032 rows x 2 columns]

In [20]:
labeled_data.to_csv('labeledData3.csv', index=False)